### ISSUE TITLE
Quick test in windows 10, error

### ISSUE THREAD

**Issue by NicoKiaru** [scijava/jaunch#1]
Hi!

I've quickly tried the repo. Without thinking much, I just cloned the repo and wrote the instructions in powershell.

I was unsure what was supposed to be the active folder when running the command, but I assume it was the repo root folder.

When attempting to run `make app` I get this error:

```
(base) PS C:\Users\nicol\Dropbox\biop\jaunch> make app
process_begin: CreateProcess(NULL, bash C:\Users\nicol\Dropbox\biop\jaunch\bin\compile-launcher.sh, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:8: compile-launcher] Error 2
```

Any idea ?

**Comment by ctrueden** [comment]
@NicoKiaru Did you install MinGW first? I think the `bash` and `make` that come with MinGW are needed...

**Comment by NicoKiaru** [comment]
Yep I did install scoop and mingw via scoop. I retried to install mingw and I get an 'already installed' message:

```
(base) PS C:\Users\nico\Dropbox\BIOP\jaunch> scoop install mingw
Updating Scoop...
Updating 'main' bucket...
 * 702bd00b5 trufflehog: Update to version 3.63.11                       45 minutes ago
 * 4f19efd2b terragrunt: Update to version 0.54.21                       45 minutes ago
 * b237934d9 resharper-clt: Update to version 2023.3.3                   45 minutes ago
 * f3387bb79 nodejs: Update to version 21.6.1                            45 minutes ago
 * b99163c8f dottrace-clt: Update to version 2023.3.3                    45 minutes ago
 * 64b872911 dotmemory-clt: Update to version 2023.3.3                   45 minutes ago
 * 268e9b7da dotcover-clt: Update to version 2023.3.3                    45 minutes ago
 * 5de311ac1 docker-compose: Update to version 2.24.2                    45 minutes ago
 * 8573dafe2 containerd: Update to version 1.7.12                        45 minutes ago
 * b0af2b538 cc65: Update to version 7615494492                          45 minutes ago
Scoop was updated successfully!
WARN  'mingw' (13.2.0-rt_v11-rev1) is already installed.
Use 'scoop update mingw' to install a new version.
(base) PS C:\Users\nicol\Dropbox\BIOP\jaunch> make app
process_begin: CreateProcess(NULL, bash C:\Users\nicol\Dropbox\BIOP\jaunch\bin\compile-launcher.sh, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:8: compile-launcher] Error 2
(base) PS C:\Users\nico\Dropbox\BIOP\jaunch>
```

Maybe it's a path issue. I'll check tomorrow.

**Comment by NicoKiaru** [comment]
Ah, no make is there:
```

(base) PS C:\Users\nicol\Dropbox\BIOP\jaunch> make --version
GNU Make 4.4.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by NicoKiaru** [comment]
Maybe that's the reason: https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified

**Comment by NicoKiaru** [comment]
A bunch of potential issues here: https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified

**Comment by NicoKiaru** [comment]
Ahah, it seems to be running within bash that comes with git for windows (but not in powershell):

![image](https://github.com/scijava/jaunch/assets/20223054/e03cbc2d-9821-4fa7-a8fc-d01a748c0cea)

**Comment by NicoKiaru** [comment]
Success!

![image](https://github.com/scijava/jaunch/assets/20223054/69481ec4-506d-4e3c-8f21-68b884698b29)

**Comment by ctrueden** [comment]
Glad you got it working!

Still, strange that on my Windows VM, I'm able to run the build in PowerShell. Maybe because my git was also installed with Scoop? I'm not sure.
