### ISSUE TITLE
Best physical memory API

### ISSUE THREAD

**Issue by ctrueden** [scijava/jaunch#29]
Jaunch Kotlin uses `ullTotalPhys` and `ullAvailPhys`, but the ImageJ Launcher uses `dwTotalPhys` and `dwAvailPhys`. What's the difference? Which one is better?

**Comment by marktsuchida** [comment]
`dw` is double word (aka `DWORD`), which is 32 bits in the Win32 API. `ull` is presumably `unsigned long long`, which is 64 bits.

**Comment by ctrueden** [comment]
Thanks @marktsuchida. So then I guess it's better that Jaunch is using `ull` here, since it's only targeting 64-bit systems.
